'use client'
import { Card, CardContent } from "@/components/ui/card"
import { HandHeart, Earth } from "lucide-react"
import { motion } from "framer-motion"

export default function MissionPage() {
  return (
    <div className="min-h-screen w-full text-cyan-50 flex flex-col justify-between p-4 sm:p-8">
      <div className="flex-grow flex items-center justify-center">
        <div className="w-full max-w-4xl">
          <h1 className="text-center">
            <motion.p
              className="block text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold leading-tight mb-6 bg-gradient-to-r from-cyan-300 via-cyan-100 to-cyan-300  text-transparent bg-clip-text"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, ease: "easeOut", delay: 0.2 }}
            >
              Our mission is to foster a world where knowledge is a shared and universal resource.
            </motion.p>
          </h1>
        </div>
      </div>
      
      <div className="w-full max-w-7xl mx-auto mt-12 grid gap-6 md:grid-cols-2">
          <div className="p-3 sm:p-4 relative bg-white bg-opacity-10 p-8 rounded-lg">
            <div className = 'flex space-x-4 p-2'>
                <HandHeart className="h-10 w-10 text-cyan-100" />
                <h2 className="text-3xl sm:text-4xl font-semibold mb-4 text-graident">
                Philanthropic Efforts
                </h2>
            </div>
            <p className="text-xl text-cyan-100">
              Excess revenue generated by Astra Pro plans is donated to organizations that provide access to educational resources
              in underserved communities.
            </p>
          </div>
        
          <div className="p-3 sm:p-4 relative bg-white bg-opacity-10 p-8 rounded-lg">
          <div className = 'flex space-x-4 p-2'>
                <Earth className="h-10 w-10 text-cyan-100" />
                <h2 className="text-3xl sm:text-4xl font-semibold mb-4 text-gradient">
                Our Motivation
                </h2>
            </div>
            <p className="text-xl text-cyan-100">
                We believe that education is a fundamental human right. Astra aims to be accesible to all by
                transforming complex academic content into engaging audio experiences.
            </p>
          </div>
      </div>
    </div>
  )
}

