version: "3.9"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auxiom_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db
    working_dir: /app
    env_file:
      - .env
    command: >
      bash -c "
      npm install &&
      if [ $DO_SEEDING = TRUE ]; then
        npm run db:migrate &&
        npm run db:seed
      fi &&
      npm run dev
      "
    networks:
      - auxiom-net

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auxiom-net

volumes:
  postgres_data:

networks:
  auxiom-net: